engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
languages:
  Ruby: true
  JavaScript: true
exclude_paths:
- "public/js/gibberish-aes-1.0.0.js"
- "public/js/jquery-3.1.1.min.js"
- spec/**/*