require 'sinatra'
require 'sinatra/activerecord'
require 'pry'
require 'byebug'
require 'haml'
require 'securerandom'

require_relative 'helpers/messages'
require_relative 'models/message'
require_relative 'models/option'
require_relative 'controllers/messages'
require_relative 'controllers/home'
